-- Generated by scripts/resolve-player-countries.mjs — do not hand-edit.
-- Source: Wikidata (P1532 country for sport, falling back to P27 citizenship).
insert into public.tennis_player_countries
  (player_name, country_iso2, country_qid, player_qid, source)
values
  ('Alexander Blockx', 'be', 'Q31', 'Q114728346', 'sport'),
  ('Alexander Bublik', 'kz', 'Q232', 'Q23678983', 'override'),
  ('Andrey Rublev', 'ru', 'Q159', 'Q17373391', 'sport'),
  ('Anhelina Kalinina', 'ua', 'Q212', 'Q15642606', 'sport'),
  ('Anna Bondar', 'hu', 'Q28', 'Q19281715', 'sport'),
  ('Barbora Krejcikova', 'cz', 'Q213', 'Q11052500', 'sport'),
  ('Clara Burel', 'fr', 'Q142', 'Q54086890', 'sport'),
  ('Daria Snigur', 'ua', 'Q212', 'Q65553008', 'sport'),
  ('Dominika Salkova', 'cz', 'Q213', 'Q113215656', 'citizenship'),
  ('Elina Avanesyan', 'am', 'Q399', 'Q106312033', 'sport'),
  ('Fiona Ferro', 'fr', 'Q142', 'Q16885515', 'sport'),
  ('Francesca Jones', 'gb', 'Q145', 'Q62700236', 'citizenship'),
  ('Hugo Gaston', 'fr', 'Q142', 'Q47483451', 'sport'),
  ('Jaime Faria', 'pt', 'Q45', 'Q125249050', 'citizenship'),
  ('Jennifer Ruggeri', 'it', 'Q38', 'Q119795145', 'citizenship'),
  ('Lanlana Tararudee', 'th', 'Q869', 'Q113162452', 'citizenship'),
  ('Lilli Tagger', 'at', 'Q40', 'Q128688561', 'citizenship'),
  ('Luca Van Assche', 'fr', 'Q142', 'Q107205896', 'sport'),
  ('Lucia Bronzetti', 'it', 'Q38', 'Q90569642', 'sport'),
  ('Luciano Darderi', 'it', 'Q38', 'Q109144854', 'citizenship'),
  ('Marie Bouzkova', 'cz', 'Q213', 'Q18003204', 'sport'),
  ('Mayar Sherif', 'eg', 'Q79', 'Q19577829', 'citizenship'),
  ('Mina Hodzic', 'de', 'Q183', 'Q65515756', 'citizenship'),
  ('Oleksandra Oliynykova', 'ua', 'Q212', 'Q105711730', 'sport'),
  ('Paula Badosa', 'es', 'Q29', 'Q19560013', 'sport'),
  ('Quentin Halys', 'fr', 'Q142', 'Q18001228', 'sport'),
  ('Roman Andres Burruchaga', 'ar', 'Q414', 'Q113870466', 'sport'),
  ('Sara Bejlek', 'cz', 'Q213', 'Q107640117', 'sport'),
  ('Tamara Korpatsch', 'de', 'Q183', 'Q19924597', 'sport'),
  ('Tereza Valentova', 'cz', 'Q213', 'Q113218343', 'sport'),
  ('Tomas Martin Etcheverry', 'ar', 'Q414', 'Q104728520', 'sport'),
  ('Yannick Hanfmann', 'de', 'Q183', 'Q29628209', 'sport'),
  ('Yasmine Kabbaj', 'ma', 'Q1028', 'Q111994096', 'citizenship')
on conflict (player_name) do update set
  country_iso2 = excluded.country_iso2,
  country_qid  = excluded.country_qid,
  player_qid   = excluded.player_qid,
  source       = excluded.source,
  resolved_at  = now();
